server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: msvc-cursos
          uri: http://localhost:8002/
          predicates:
            - Path=/cursos/**
        - id: msvc-usuarios
          uri: http://localhost:8001/
          predicates:
            - Path=/usuarios/**



